### ISSUE TITLE
Does not work together with angular-material

### ISSUE THREAD

**Issue by ghost** [LukaszWatroba/v-textfield#1]
Hi!
I use angular-material to build a dashboard like webapp.
When I try to copy and paste v-textfield, it basically works, but does not show the error messages.
Do you know, what could be the problem here?

**Comment by LukaszWatroba** [comment]
The directive itself only adds a few classes on the v-textfield element. You can try to customize the CSS file for your needs. 
vTextfield is an alternative to angular-material and md-input-container directive. I don't recommend using them both.

**Comment by LukaszWatroba** [comment]
Hey @happschinson. Can I close this issue now?
